-- Dummy FEATURES_OF_INTEREST view for local FROST setup
DROP VIEW IF EXISTS "FEATURES_OF_INTEREST" CASCADE;
CREATE VIEW "FEATURES_OF_INTEREST" AS
SELECT
    NULL::bigint AS "ID",
    NULL::varchar AS "NAME",
    NULL::varchar AS "DESCRIPTION",
    NULL::varchar AS "ENCODING_TYPE",
    NULL::jsonb  AS "FEATURE"
WHERE false;
