-- Dummy HISTORICAL_LOCATIONS view for local FROST setup
DROP VIEW IF EXISTS "HISTORICAL_LOCATIONS" CASCADE;
CREATE VIEW "HISTORICAL_LOCATIONS" AS
SELECT
    NULL::bigint AS "ID",
    NULL::timestamptz AS "TIME",
    NULL::bigint AS "THING_ID",
    NULL::bigint AS "LOCATION_ID"
WHERE false;
