-- Dummy OBSERVED_PROPERTIES view for local FROST setup
DROP VIEW IF EXISTS "OBSERVED_PROPERTIES" CASCADE;
CREATE VIEW "OBSERVED_PROPERTIES" AS
SELECT
    NULL::bigint AS "ID",
    NULL::varchar AS "NAME",
    NULL::varchar AS "DEFINITION",
    NULL::varchar AS "DESCRIPTION"
WHERE false;
